apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: string-grpc
build:
  artifacts:
    - image: string-grpc
      ko:
        fromImage: gcr.io/distroless/static:nonroot
  tagPolicy:
    inputDigest: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml