apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: string-grpc
  template:
    metadata:
      labels:
        app: string-grpc
    spec:
      containers:
      - name: string-grpc
        image: string-grpc
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        resources:
          requests:
            cpu: 50m
            ephemeral-storage: 128Mi
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 8081
